project:
  type: website
  output-dir: docs

website:
  title: "Qinya Feng"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: default
    css: styles.css
    toc: true
    fontsize: 1.1em
    page-layout: full

editor: visual

